---
- name: Common ansible playbook
  hosts: all

  roles:
    - { role: apache, when: php_engine == 'apache' }
    - common
    - ntp
    - git
    - rmate
    - { role: php-apache, when: php_engine == 'apache' }
    - { role: php-fpm, when: php_engine == 'fpm' }
    - { role: php-hhvm, when: php_engine == 'hhvm' }
    - php-extensions
    - php-maxmind-geoip
    - php-newrelic
    - php-phalcon
    - php-zmq
    - composer
    - { role: nginx, when: php_engine != 'apache' }
    - mysql
    - cassandra
    - python
    - sharedance
    - redis
    - elasticsearch
    - scout_realtime
    - zeromq