---
- name: register dotdeb key
  apt_key: url=http://www.dotdeb.org/dotdeb.gpg state=present
  
- name: add dotdeb default repositories
  apt_repository: repo='deb http://packages.dotdeb.org {{ debian }} all' state=present

- name: add dotdeb php55 repositories
  apt_repository: repo='deb http://packages.dotdeb.org {{ debian }}-php55 all' state=present

- name: add dotdeb php55 sources repositories
  apt_repository: repo='deb-src http://packages.dotdeb.org {{ debian }}-php55 all' state=present

- name: install php packages
  apt: pkg={{ item }} state=latest force=yes
  with_items:
    - php5-curl
    - php5-dbg
    - php5-intl
    - php5-mcrypt
    - php5-mysqlnd
    - php5-apcu
    - php5-geoip
    - php5-imagick
    - php5-memcache
    - php5-mongo
    - php5-readline
    - php5-redis
    - php5-xdebug
