---
- name: check predictionio
  stat: path=/usr/local/sbin/PredictionIO-{{ predictionio.version }}
  register: predictionpath

- name: install required packages
  apt: pkg={{ item }} state=latest
  with_items:
    - unzip
    - openjdk-7-jdk
    - mongodb-org

- name: download archive
  get_url: url=http://download.prediction.io/PredictionIO-{{ predictionio.version }}.zip dest=/tmp/PredictionIO-{{ predictionio.version }}.zip
  when: predictionpath.stat.isdir is not defined

- name: extract archive
  # unarchive: src="/tmp/PredictionIO-{{ predictionio.version }}.zip" dest=/usr/local/sbin
  command: "{{ item }}"
  with_items:
      - unzip /tmp/PredictionIO-{{ predictionio.version }}.zip -d /usr/local/sbin
      - rm -f /tmp/PredictionIO-{{ predictionio.version }}.zip
      - /usr/local/sbin/PredictionIO-{{ predictionio.version }}/bin/setup.sh
  when: predictionpath.stat.isdir is not defined

- name: copy init.d
  template: src=predictionio.j2 dest=/etc/init.d/predictionio mode=0755
  notify: restart predictionio

- name: start predictionio on boot
  action: command {{ item }} chdir=/etc/init.d/
  with_items:
    - update-rc.d predictionio defaults