---
- name: use french debian mirror
  template: src=sources.list.j2 dest=/etc/apt/sources.list

- name: upgrade the distro
  apt: update_cache=yes upgrade=yes cache_valid_time=3600

- name: install common packages
  apt: pkg={{ item }} state=latest
  with_items:
    - vim
    - curl
    - gnupg
    - rsync
    - wget
    - ack-grep
    - python-pycurl
